name: ComposeEx PR Builder
on:
  pull_request:
    branches: [ main ]
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  build:
    name: PR Checker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 1.8
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Access Local Properties
        env:
          HFM_BASE_URL: ${{ secrets.BASE_URL }}
        run: echo "base.url=\"$BASE_URL\"" >> local.properties

      - name: Lint Check
        run: ./gradlew ktlintCheck -PcompileSdkVersion=34

      - name: Build with Gradle
        run: ./gradlew build
